Repository AY1920S2-CS2103T-W12-3/main, pull requests merged in 2020-04, with the labels that each got.

#194 Updating user guide
  docs/UserGuide.adoc
Labels: documentation

#182 Add tests
  src/main/java/seedu/address/logic/parser/SharkieParser.java
  src/main/java/seedu/address/model/transaction/Date.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/people/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/wallet/EditTransactionDescriptorTest.java
  src/test/java/seedu/address/logic/commands/wallet/WalletEditCommandTest.java
  src/test/java/seedu/address/logic/parser/SharkieParserTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/UserTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/BudgetListTest.java
  src/test/java/seedu/address/model/transaction/DateContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/transaction/DateTest.java
  src/test/java/seedu/address/model/transaction/DebtTest.java
  src/test/java/seedu/address/model/transaction/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBudgetTest.java
  src/test/java/seedu/address/testutil/WalletUtil.java
Labels: type.Task

#200 Update DG
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/Testing.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelManagerClassDiagram.puml
  docs/diagrams/ModelPersonDiagram.puml
  docs/diagrams/ModelReminderClassDiagram.puml
  docs/diagrams/ModelTransactionClassDiagram.puml
  docs/diagrams/ModelTransactionDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/ModelManagerClassDiagram.png
  docs/images/ModelPersonDiagram.png
  docs/images/ModelReminderClassDiagram.png
  docs/images/ModelTransactionClassDiagram.png
  docs/images/ModelTransactionDiagram.png
Labels: documentation

#248 Add wallet clear command
  src/main/java/seedu/address/logic/commands/wallet/WalletClearCommand.java
  src/main/java/seedu/address/logic/parser/SharkieParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Wallet.java
  src/test/java/seedu/address/logic/commands/wallet/WalletClearCommandTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Enhancement

#192 Update UG - Syin Yi
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelPersonDiagram.puml
  docs/diagrams/ModelReminderClassDiagram.puml
  docs/diagrams/ModelTransactionClassDiagram.puml
  docs/diagrams/ModelTransactionDiagram.puml
  docs/diagrams/ReceivedActivityDiagram.puml
  docs/diagrams/ReceivedSequenceDiagram.puml
  docs/images/DebtAndLoanDifferences.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelPersonDiagram.png
  docs/images/ModelReminderClassDiagram.png
  docs/images/ModelTransactionClassDiagram.png
  docs/images/ModelTransactionDiagram.png
  docs/images/ReceivedActivityDiagram.png
  docs/images/ReceivedSequenceDiagram.png
  docs/images/loanDebtIndexFAQ.png
  docs/images/personIndexFAQ.png
  docs/team/syinyichen.adoc
  docs/team/syinyichen.html
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: documentation

#242 Update UG - Daniel
  docs/UserGuide.adoc
Labels: documentation

#197 Update UG - Grace
  docs/UserGuide.adoc
  docs/images/EnterPinData.png
  docs/images/EnterUserData.png
  docs/team/gracegrape.adoc
Labels: documentation

#196 Update UG and DG - Cheyanne
  docs/UserGuide.adoc
  docs/diagrams/OweActivityDiagram.puml
  docs/diagrams/OweSequenceDiagram.puml
  docs/images/OweActivityDiagram.png
  docs/images/OweSequenceDiagram.png
  docs/team/cheyannesim.adoc
  src/main/java/seedu/address/logic/parser/people/PeopleOweCommandParser.java
Labels: documentation

#249 Send confirmation email to confirm user's email
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelReminderClassDiagram.puml
  docs/images/ModelReminderClassDiagram.png
  docs/team/syinyichen.adoc
  docs/team/syinyichen.html
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/people/PeopleRemindAllCommand.java
  src/main/java/seedu/address/logic/commands/people/PeopleRemindCommand.java
  src/main/java/seedu/address/model/reminder/ConfirmationEmail.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/EnterUserDataWindow.java
  src/main/resources/view/EnterUserDataWindow.fxml
  src/test/java/seedu/address/model/reminder/ConfirmationEmailTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
Labels: type.Enhancement

#256 Update DG - Cheyanne
  docs/DeveloperGuide.adoc
  docs/team/cheyannesim.adoc
Labels: documentation

#252 Update UG - Joel
  docs/UserGuide.adoc
Labels: documentation

#255 Update more Documentation - Grace
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/gracegrape.adoc
  src/main/java/seedu/address/logic/commands/wallet/WalletFindCommand.java
Labels: documentation

#254 Update DG - Daniel
  docs/DeveloperGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/WalletBudgetSequenceDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/WalletBudgetSequenceDiagram.png
Labels: documentation

#257 Update DG - Joel
  docs/diagrams/ExpenseActivityDiagram.puml
  docs/diagrams/ExpenseSequenceDiagram.puml
  docs/images/ExpenseActivityDiagram.png
  docs/images/ExpenseSequenceDiagram.png
Labels: documentation

#260 User guide vetting
  docs/UserGuide.adoc
  docs/images/transactionIndexFAQ.jpg
Labels: documentation
